name: Build SingleFile
on:
  push:
    branches:
      - main
jobs:
  build:
    env:
      BUILD_TYPE: REL
      SENTRY_URL: ${{ secrets.SENTRY_URL }}
      SENTRY_KEY: ${{ secrets.SENTRY_KEY }}
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Unpack git objects
        run: |
          mv .git/objects/pack .
          git unpack-objects < pack/*.pack
          rm -rf pack
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          architecture: 'x64'
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build:singlefile      
      - name: Rename
        run: mkdir dist/local && mv dist/index.html dist/local/cocogoat-web-local.html
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: cocogoat-local
          path: dist/local/